### ISSUE TITLE
Feature Request / RFC: Allow closures in cached config for lean object construction

### ISSUE THREAD

**Issue by bcremer** [laminas/laminas-config-aggregator#6]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

### Summary

Right now it is not possible to use closures in a `ConfigProvider` or PHP Config file if [config caching](https://docs.laminas.dev/laminas-config-aggregator/caching/) is enabled (`ConfigAggregator::ENABLE_CACHE => true`).

Example:

```php
// config/autoload/dependencies.global.php
return [
    'dependencies' => [
        'factories'  => [
            SomeService::class => fn() => new SomeService(),
        ],
    ],
];
```

When calling the application and thus calling `\Laminas\ConfigAggregator\ConfigAggregator::__construct()` the first request will be fine and working like expected, also the cached config is generated and sucessfully written to `config_cache_path`.

On the second call the config is read from the cache file and will fail with the following exception message:

```
$ php bin/console.php 
PHP Fatal error:  Uncaught Error: Call to undefined method Closure::__set_state() in /example/data/cache/config-cache.php:186
Stack trace:
#0 /example/vendor/laminas/laminas-config-aggregator/src/ConfigAggregator.php(257): require()
#1 /example/vendor/laminas/laminas-config-aggregator/src/ConfigAggregator.php(76): Laminas\ConfigAggregator\ConfigAggregator->loadConfigFromCache()
```

This is due to the fact that PHP natives [`var_export`](https://www.php.net/var_export) is used to generate the cache file contents, see: https://github.com/laminas/laminas-config-aggregator/blob/1.2.2/src/ConfigAggregator.php#L281

### Proposed solution

Instead of the PHP native `var_export` function the ConfigAggregator should optionally use a library that is able to export closures into a native PHP array.

I successfully implemented a POC using [brick/varexporter](https://github.com/brick/varexporter) by @BenMorel that provides a drop in replacement for `var_export` and is able to [export closures](https://github.com/brick/varexporter#exporting-closures).

#### Problem

A typical service in a laminas/mezzio application uses a separate factory class to resolve dependencies from the `ContainerInterface` and to instantiate the service.

```php
<?php

namespace App\Api\Search;

use Doctrine\DBAL\Connection;
use Psr\Container\ContainerInterface;
use Psr\Logger\LoggerInterface;

final class SearchRepositoryFactory
{
    public function __invoke(ContainerInterface $container): SearchRepository
    {
        return new SearchRepository(
            $container->get(Connection::class),
            $container->get(LoggerInterface::class),
        );
    }
}
```

Additionally the factory must be registered in the config file or a ConfigProvider like so:

```php
return [
    'dependencies' => [
        'factories'  => [
            SearchRepositoryFactory::class => SearchRepositoryFactory::class,
        ],
    ],
];
```

This is a lot of boilerplate code to introduce a new service into an application.

#### Proposed solution

With the introduction of Arrow functions in PHP 7.4 the factory code can be written in a very lean way in the config provider or config file like this:

```php

<?php

use Doctrine\DBAL\Connection;
use Psr\Container\ContainerInterface;
use Psr\Logger\LoggerInterface;

return [
    'dependencies' => [
        'factories'  => [
            SearchRepository::class => fn (ContainerInterface $container) => new SearchRepository(
                $container->get(Connection::class),
                $container->get(LoggerInterface::class),
            ),

            AnotherService::class => fn (ContainerInterface $container) => new AnotherService(
                $container->get(LoggerInterface::class),
                $container->get(SystemClock::class)
            ),
        ],
    ],
];
```

In my opinion the this provides a good middle ground between the convenience of the `ReflectionBasedAbstractFactory` and the control and performance of manually written factory classes.

I'm not proposing to get rid of all factory classes but only factory classes that contain no logic but resolving and instantiating the given service class.
I'm still using dedicated factory class for any object construction logic that is more complicated.

### Performance Considerations

The exported closures look like the following in the generated cache files:

```php
        'factories' => [
            'App\\Api\\Search\\SearchRepository' => function (\Psr\Container\ContainerInterface $container) {
                return new \App\Api\Search\SearchRepository($container->get(\Doctrine\DBAL\Connection::class));
            },
        ]
```

#### Performance related questions:
- Can the generated cache file still be picked up into the opcache
- Is calling the closures slower than calling instantiating and calling factory classes?

### Alternative approaches
- https://github.com/reinfi/zf-dependency-injection

### Questions
- How do you feel generally about using Arrow functions instead of factory classes?
- Can a third party library like [brick/varexporter](https://github.com/brick/varexporter) be a viable solution to export closures in the cached config file?
- How should this be implemented
    - `brick/varexporter` could be used a soft dependecy and used instead of the native function when available
- Are you open for an PR implementing the proposed solution either as a separate ConfigAggregator or as the soft dependency or maybe a postprocessor? I'm open for implementation ideas.

**Comment by Ocramius** [comment]
Overall, I think this makes sense, and is a good improvement with little drawback (added dependency).

@BenMorel's work is excellent, so I can totally vouch for it :+1:

**Comment by asgrim** [comment]
+1, I like the proposal. I think the question is; do want to add a hard dependency, soft dependency, etc

As for arrow functions, depends on the target PHP version really 😁

**Comment by bcremer** [comment]
> do want to add a hard dependency, soft dependency, etc

`brick/varexporter` depends on `nikic/php-parser` so that would be a rather hefty non dev dependency for a small package like ` laminas/laminas-config-aggregator`.

**Comment by bcremer** [comment]
Implemented as soft dependency for now as base for further discussions:
https://github.com/laminas/laminas-config-aggregator/pull/7

**Comment by Xerkus** [comment]
I am on a fence about closure support, since they are necessary a generated code and that is a whole new can of worms.
I think it is generally undesirable to use closures in config providers as closures would need to be created every time config is loaded.

With the existing aggregator, closures could be used in application level config with two step setup split into cacheable and non-cacheable parts:
 
```php
$cachingAggregator = new ConfigAggregator([
    new ArrayProvider($cacheConfig),
    \Foo\ConfigProvider::class,
    new PhpFileProvider(realpath(__DIR__) . '/autoload/{,*.}global.php'),
], $cacheConfig['config_cache_path']);

$aggregator = new ConfigAggregator([
    new ArrayProvider($cachingAggregator->getMergedConfig()),
    new PhpFileProvider(realpath(__DIR__) . '/autoload/{{,*.}global.nocache,{,*.}local}.php'),
], null);
return $aggregator->getMergedConfig();
```
I use this approach for the config that uses environment and portions of it should not be cached. It only covers the very specific usage and partially defeats the caching.

I have some thoughts I'll share later on how we can improve design with major usage change. I mean, not BC breaking change, but it would probably be more suitable for the new major anyway.
As it is I would probably oppose the feature as it would be doing too much.

On a related note, objects can be used with cached config if they implement `__set_state()` magic method. That opens a way for reusing factories with different sets of dependencies eg if saved and set state is a mapping of container keys for dependencies.
Downside is as with the closures - those objects are going to be instantiated every time config is loaded.

**Comment by weierophinney** [comment]
I don't think we'd recommend using closures in package config providers. However, for end-user applications, there are some significant benefits to readability and understanding of code, particularly when all you are doing is pulling deps from the container and using them to seed and return the requested instance.

After looking at what brick/varexporter actually does for things like closures, my suspicion is that this will have negligible impact on the performance of cached configuration, since it essentially just writes the closures into the exported code. Creation of closures tends to be a very fast operation as well; if you're so concerned with performance that you want to optimize those out, create a factory class and reference it by name instead.

There will be more impact when using actual class instances when they do not implement `__set_state()` or `_serialize()`/`__unserialize()`; fortunately, this is a niche case, and that performance impact is mainly due to usage of reflection — which is having less and less impact with each new PHP version.
